export const NEARBY_CITIES = [
  "Milton",
  "Mississauga",
  "Brampton",
  "Oakville",
  "Burlington",
  "Hamilton",
  "Ancaster",
  "Toronto",
  "Etobicoke",
  "North York",
  "Scarborough",
  "Vaughan",
  "Woodbridge",
  "Concord",
  "Markham",
  "Richmond Hill",
  "Whitchurch-Stouffville",
  "Georgetown",
  "Halton Hills",
  "Acton",
  "Guelph",
  "Cambridge",
  "Kitchener",
  "Waterloo",
  "Brantford",
  "Stoney Creek",
  "Grimsby",
  "Dundas",
  "Caledon",
  "Bolton",
  "Paris",
  "Ayr",
  "Flamborough",
  "Ajax",
  "Pickering",
  "Oshawa"
];
