create table if not exists public.vendor_contacts (
  id bigint generated by default as identity primary key,
  vendor_id bigint not null references public.vendors(id) on delete cascade,
  name text not null,
  title text,
  linkedin text,
  created_at timestamptz not null default now()
);

create index if not exists vendor_contacts_vendor_id_idx
  on public.vendor_contacts(vendor_id);

insert into public.vendor_contacts (vendor_id, name, title)
select v.id, btrim(v.name), nullif(btrim(v.title), '')
from public.vendors as v
where nullif(btrim(v.name), '') is not null
  and not exists (
    select 1
    from public.vendor_contacts as vc
    where vc.vendor_id = v.id
      and lower(vc.name) = lower(btrim(v.name))
  );
